version: 2

project_name: bai

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/bai
    binary: bai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
        -X "main.version={{.Version}}"
        -X "main.commit={{.Commit}}"
        -X "main.date={{.Date}}"

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - readme
      - LICENSE
      - config.example.json

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
  groups:
    - title: "Features"
      regexp: "^feat:"
      order: 0
    - title: "Fixes"
      regexp: "^fix:"
      order: 1
    - title: "Refactors"
      regexp: "^refactor:"
      order: 2
    - title: "Others"
      order: 999

release:
  github:
    owner: biisal
    name: bai
  prerelease: auto
  header: |
    # bAI {{ .Tag }}

    ## Changelog
  footer: |
    ---
    _Released with [GoReleaser](https://goreleaser.com)_