// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package repo

import (
	"context"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (title , directory) VALUES (?1 , ?2) RETURNING id, title, directory, created_at, updated_at
`

type CreateConversationParams struct {
	Title     string
	Directory string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.Title, arg.Directory)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, directory, created_at, updated_at FROM conversations WHERE id = ?1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationsByDirectory = `-- name: GetConversationsByDirectory :many
SELECT id, title, directory, created_at, updated_at FROM conversations WHERE directory = ?1 ORDER by id DESC
`

func (q *Queries) GetConversationsByDirectory(ctx context.Context, directory string) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByDirectory, directory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Directory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
