// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package repo

import (
	"context"
	"time"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (title , directory) VALUES (?1 , ?2) RETURNING id, title, directory, created_at, updated_at
`

type CreateConversationParams struct {
	Title     string
	Directory string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.Title, arg.Directory)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = ?1
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, directory, created_at, updated_at FROM conversations WHERE id = ?1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMessageCount = `-- name: GetConversationMessageCount :one
SELECT COUNT(*) FROM messages WHERE conversation_id = ?1
`

func (q *Queries) GetConversationMessageCount(ctx context.Context, conversationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getConversationMessageCount, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConversationsByDirectory = `-- name: GetConversationsByDirectory :many
SELECT id, title, directory, created_at, updated_at FROM conversations WHERE directory = ?1
`

func (q *Queries) GetConversationsByDirectory(ctx context.Context, directory string) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByDirectory, directory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Directory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, created_at, updated_at FROM conversations ORDER BY updated_at DESC
`

type ListConversationsRow struct {
	ID        int64
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListConversations(ctx context.Context) ([]ListConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE conversations SET title = ?1, updated_at = datetime('now') WHERE id = ?2
`

type UpdateConversationParams struct {
	Title string
	ID    int64
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateConversation, arg.Title, arg.ID)
	return err
}
