// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory_settings.sql

package repo

import (
	"context"
)

const getDirectorySettings = `-- name: GetDirectorySettings :one
SELECT id, directory, auto_git_init FROM directory_settings
WHERE directory = ?1
`

func (q *Queries) GetDirectorySettings(ctx context.Context, directory string) (DirectorySetting, error) {
	row := q.db.QueryRowContext(ctx, getDirectorySettings, directory)
	var i DirectorySetting
	err := row.Scan(&i.ID, &i.Directory, &i.AutoGitInit)
	return i, err
}

const upsertDirectorySettings = `-- name: UpsertDirectorySettings :exec
INSERT INTO directory_settings (directory, auto_git_init)
VALUES (?1, ?2)
ON CONFLICT(directory) DO UPDATE SET auto_git_init = excluded.auto_git_init
`

type UpsertDirectorySettingsParams struct {
	Directory   string
	AutoGitInit bool
}

func (q *Queries) UpsertDirectorySettings(ctx context.Context, arg UpsertDirectorySettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDirectorySettings, arg.Directory, arg.AutoGitInit)
	return err
}
