// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory_settings.sql

package repo

import (
	"context"
)

const createDirectorySettings = `-- name: CreateDirectorySettings :exec
INSERT INTO directory_settings (directory, auto_git_init)
VALUES (?1, ?2)
`

type CreateDirectorySettingsParams struct {
	Directory   string
	AutoGitInit bool
}

func (q *Queries) CreateDirectorySettings(ctx context.Context, arg CreateDirectorySettingsParams) error {
	_, err := q.db.ExecContext(ctx, createDirectorySettings, arg.Directory, arg.AutoGitInit)
	return err
}

const getDirectorySettings = `-- name: GetDirectorySettings :one
SELECT id, directory, auto_git_init FROM directory_settings
WHERE directory = ?1
`

func (q *Queries) GetDirectorySettings(ctx context.Context, directory string) (DirectorySetting, error) {
	row := q.db.QueryRowContext(ctx, getDirectorySettings, directory)
	var i DirectorySetting
	err := row.Scan(&i.ID, &i.Directory, &i.AutoGitInit)
	return i, err
}

const updateDirectorySettings = `-- name: UpdateDirectorySettings :exec
UPDATE directory_settings
SET auto_git_init = ?2
WHERE directory = ?1
`

type UpdateDirectorySettingsParams struct {
	Directory   string
	AutoGitInit bool
}

func (q *Queries) UpdateDirectorySettings(ctx context.Context, arg UpdateDirectorySettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateDirectorySettings, arg.Directory, arg.AutoGitInit)
	return err
}
