// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/biisal/bai/internal/domain"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id,
    role,
    parts,
    error
) VALUES (
    ?1, ?2, ?3, ?4
) RETURNING id
`

type CreateMessageParams struct {
	ConversationID int64
	Role           domain.Role
	Parts          string
	Error          sql.NullString
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Parts,
		arg.Error,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, role, parts, error, created_at, finished_at
FROM messages
WHERE conversation_id = ?1
ORDER BY id ASC
`

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Parts,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
