// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ID        int64
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	Error          sql.NullString
	CreatedAt      time.Time
}

type ToolCall struct {
	ID        int64
	MessageID int64
	CallID    string
	Name      string
	Arguments string
	Result    sql.NullString
	IsError   int64
	Status    string
	CreatedAt time.Time
}
