// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"time"

	"github.com/biisal/bai/internal/domain"
)

type ChatCompletion struct {
	ID             any
	ConversationID sql.NullInt64
	Role           sql.NullString
	Content        sql.NullString
	Error          sql.NullString
}

type Conversation struct {
	ID        int64
	Title     string
	Directory string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID             int64
	ConversationID int64
	Role           domain.Role
	Parts          string
	Error          sql.NullString
	CreatedAt      time.Time
	FinishedAt     sql.NullTime
}

type Provider struct {
	ID           any
	ProviderName sql.NullString
	ModelID      sql.NullString
	CreatedAt    time.Time
}

type UserSetting struct {
	ID    any
	Theme sql.NullString
}
