// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package repo

import (
	"context"
	"database/sql"
)

const addOrUpdateProvider = `-- name: AddOrUpdateProvider :exec
INSERT INTO provider (id , name, provider_id, model_id) VALUES (1 , ?1, ?2, ?3) ON CONFLICT (id) DO UPDATE SET name = ?1, provider_id = ?2, model_id = ?3
`

type AddOrUpdateProviderParams struct {
	Name       string
	ProviderID sql.NullString
	ModelID    sql.NullString
}

func (q *Queries) AddOrUpdateProvider(ctx context.Context, arg AddOrUpdateProviderParams) error {
	_, err := q.db.ExecContext(ctx, addOrUpdateProvider, arg.Name, arg.ProviderID, arg.ModelID)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, provider_id, model_id, created_at FROM provider WHERE id = 1
`

func (q *Queries) GetProvider(ctx context.Context) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
	)
	return i, err
}
