// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package repo

import (
	"context"
	"database/sql"
)

const addOrUpdateProvider = `-- name: AddOrUpdateProvider :exec
INSERT 
	INTO provider (id , provider_name, model_id) 
	VALUES (1 , ?1, ?2) 
		ON CONFLICT (id) 
		DO UPDATE 
		SET provider_name = ?1, model_id = ?2
`

type AddOrUpdateProviderParams struct {
	ProviderName sql.NullString
	ModelID      sql.NullString
}

func (q *Queries) AddOrUpdateProvider(ctx context.Context, arg AddOrUpdateProviderParams) error {
	_, err := q.db.ExecContext(ctx, addOrUpdateProvider, arg.ProviderName, arg.ModelID)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, provider_name, model_id, created_at FROM provider WHERE id = 1
`

func (q *Queries) GetProvider(ctx context.Context) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.ModelID,
		&i.CreatedAt,
	)
	return i, err
}
