// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddOrUpdateProvider(ctx context.Context, arg AddOrUpdateProviderParams) error
	AddOrUpdateSettings(ctx context.Context, theme sql.NullString) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error)
	GetConversation(ctx context.Context, id int64) (Conversation, error)
	GetConversationsByDirectory(ctx context.Context, directory string) ([]Conversation, error)
	GetMessagesByConversation(ctx context.Context, conversationID int64) ([]Message, error)
	GetProvider(ctx context.Context) (Provider, error)
	GetSettings(ctx context.Context) (UserSetting, error)
}

var _ Querier = (*Queries)(nil)
