// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package repo

import (
	"context"
	"database/sql"
)

const addOrUpdateSettings = `-- name: AddOrUpdateSettings :exec
INSERT 
	INTO user_settings (id, theme) 
	VALUES (1, ?1) 
		ON CONFLICT (id) 
		DO UPDATE 
		SET theme = ?1
`

func (q *Queries) AddOrUpdateSettings(ctx context.Context, theme sql.NullString) error {
	_, err := q.db.ExecContext(ctx, addOrUpdateSettings, theme)
	return err
}

const getSettings = `-- name: GetSettings :one
SELECT id, theme FROM user_settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i UserSetting
	err := row.Scan(&i.ID, &i.Theme)
	return i, err
}
